### ISSUE TITLE
QGIS 2.18.5 crash on plugin install

### ISSUE THREAD

**Issue by frankmhowell** [sandrofsousa/Segreg#1]
I just attempted to install your plugin (thanks!) and it crashes QGIS 2.18.5 (see below) on Linux Mint (latest) on Cinnamon desktop.

Thoughts?

Frank Howell

QGIS version
2.18.5
QGIS code revision
140a01f
Compiled against Qt
4.8.7
Running against Qt
4.8.7
Compiled against GDAL/OGR
2.1.3
Running against GDAL/OGR
2.1.3
Compiled against GEOS
3.5.1-CAPI-1.9.1
Running against GEOS
3.5.1-CAPI-1.9.1 r4246
PostgreSQL Client Version
9.5.2
SpatiaLite Version
4.3.0a
QWT Version
5.2.3
PROJ.4 Version
492
QScintilla2 Version
2.9.1

**Comment by sandrofsousa** [comment]
Hi Frank, thanks for the feedback. I was able to install and run the plugin without problems on a new VM running Debian Jessie. Have you installed Scipy before? Do you have any customization or development involving QT (using same directory)? Can you give more details when it crashed? installation, first open...

**Comment by frankmhowell** [comment]
Hi,

Linux Mint is an ubuntu derivative. I keep scipy (and numpy) updated due to other apps that use them (R, etc.). SegReg crashed qgis during the plugin install. I've deleted the segreg directory and qgis executes fine. But will crash qgis upon the next attempt at installing the plugin via the plugin manager.

No customizations of Qt on my install.

Does this help? Do you have a VM of Linux Mint 18.2 to test?

Sincerely,

Frank

---
Frank M. Howell, PhD
Ridgeland, MS
frankmhowell (at) hotmail.com<http://hotmail.com>
---

On Mar 31, 2017, at 3:53 PM, Sandro Sousa <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Frank, thanks for the feedback. I was able to install and run the plugin without problems on a new VM running Debian Jessie. Have you installed Scipy before? Do you have any customization or development involving QT (using same directory)? Can you give more details when it crashed? installation, first open...

**Comment by sandrofsousa** [comment]
I will set up a VM with Mint and try to replicate the crash. I guess you are using 64-bits. Can you try to download the plugin's zip file from Github repo and add it manually to your plugins directory? Maybe adding it locally makes possible to see an error on the log messages panel.

**Comment by frankmhowell** [comment]
Sandro,


I downloaded the plugin zip library and added it manually to my .qgis2 plugin subdirectory. QGIS would not successfully execute. No message, unfortunately...just did not get that far. Scipy is version 0.17.0-1.


Sincerely,


Frank


----
Frank M. Howell, Ph.D.
416 Bay Cove
Ridgeland, MS
frankmhowell (at) hotmail.com (e-mail)
----


________________________________

**Comment by sandrofsousa** [comment]
Hi Frank, I runned a VM with Mint Cinnamon 18-1 64, QGIS version 2.14 and hadn't any issue using the plugin (after several problems with broken dependencies using apt-get I gave up with version 2.18). Maybe it's something related to your QGIS installation, you can also try to remove the preferences file at `$HOME/.config/QuantumGIS/qgis.conf` - removing it QGIS will create a new on next start up, make sure to save it for restore after the test. Sorry for not being of so much help but this kind of crash is really hard to find what is causing it.

**Comment by frankmhowell** [comment]
Sandro,

Thanks. I'll try the qgis.conf removal. The 2.18 broken dependencies have now been fixed but the rebuild of qgis against the latest gdal may not have hit your repository yet. Mine did earlier this week. So, for the time, you may not in your plugin abstract that it may not be compatible with 2.18.

I will confirm back to you early next week if the qgis.conf file removal solves the problem.

Sincerely,

Frank

---
Frank M. Howell, PhD
Ridgeland, MS
frankmhowell (at) hotmail.com<http://hotmail.com>
---

On Apr 1, 2017, at 8:41 AM, Sandro Sousa <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Frank, I runned a VM with Mint Cinnamon 18-1 64, QGIS version 2.14 and hadn't any issue using the plugin (after several problems with broken dependencies using apt-get I gave up with version 2.18). Maybe it's something related to your QGIS installation, you can also try to remove the preferences file at $HOME/.config/QuantumGIS/qgis.conf - removing it QGIS will create a new on next start up, make sure to save it for restore after the test. Sorry for not being of so much help but this kind of crash is really hard to find what is causing it.

**Comment by frankmhowell** [comment]
Sandro,

I tried the qgis.conf removal...same result. You might test it again when you get the 2.18 dependencies resolved.

Sincerely,

Frank

---
Frank M. Howell, PhD
Ridgeland, MS
frankmhowell (at) hotmail.com<http://hotmail.com>
---

On Apr 1, 2017, at 9:08 AM, Frank Howell <frankmhowell@hotmail.com<mailto:frankmhowell@hotmail.com>> wrote:

Sandro,

Thanks. I'll try the qgis.conf removal. The 2.18 broken dependencies have now been fixed but the rebuild of qgis against the latest gdal may not have hit your repository yet. Mine did earlier this week. So, for the time, you may not in your plugin abstract that it may not be compatible with 2.18.

I will confirm back to you early next week if the qgis.conf file removal solves the problem.

Sincerely,

Frank

---
Frank M. Howell, PhD
Ridgeland, MS
frankmhowell (at) hotmail.com<http://hotmail.com>
---

On Apr 1, 2017, at 8:41 AM, Sandro Sousa <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Frank, I runned a VM with Mint Cinnamon 18-1 64, QGIS version 2.14 and hadn't any issue using the plugin (after several problems with broken dependencies using apt-get I gave up with version 2.18). Maybe it's something related to your QGIS installation, you can also try to remove the preferences file at $HOME/.config/QuantumGIS/qgis.conf - removing it QGIS will create a new on next start up, make sure to save it for restore after the test. Sorry for not being of so much help but this kind of crash is really hard to find what is causing it.

**Comment by sandrofsousa** [comment]
Hi Frank,
I finished the setup to match with your environment, the plugin worked perfectly in my VM and I couldn't simulate the crash. Unfortunately looks like there is a problem with your installation, you could try removing it completely and reinstalling. In addition, there's a new version (2.18.7) that could solve the crash, it is available at - ppa:ubuntugis/ubuntugis-unstable.
I'm closing the issue and sorry for not being of more help.
