### ISSUE TITLE
ValueError: all the input array dimensions except for the concatenation axis must match exactly

### ISSUE THREAD

**Issue by giacfalk** [sandrofsousa/Segreg#3]
When I import a shapefile into segreg, select the attributes (groups) and data ID field cicking on Confirm Selection, i get the following Phython error message:

"ValueError: all the input array dimensions except for the concatenation axis must match exactly".

Is there any characteristic of the shapefile which might disturb the script?

**Comment by sandrofsousa** [comment]
Would be helpful if you send the full error message from python so I can check the exact line code where it breaks. My guess is may exist empty values (null) in your attribute data. Can you check if this is the case? In case positive, filling them with zero would avoid the issue.

**Comment by giacfalk** [comment]
Dear Sandro, thanks it worked by removing some empty features. Still, when I compute segregaiton measures, the measures in the output csv file are empty. May I forward my shapefile to you so that you can check?
