### ISSUE TITLE
Unable to save results

### ISSUE THREAD

**Issue by airhill007** [sandrofsousa/Segreg#4]
I am setting the  different bandwidths for a spatial dissimilarity analysis but I am getting the same results for whatever number I enter in : 500, 700 or 1000 mts. I am following the instructions given on how to run the spatial analysis so I don't exactly where it is going wrong. Any suggestions.....

**Comment by sandrofsousa** [comment]
Could you please be more specific, Is there any error msg? Have you tested on different shape files with the same behaviour? Make sure you are using a correct projected CRS.

**Comment by airhill007** [comment]
No problems! All sorted.

Regards,

C


________________________________
