### ISSUE TITLE
Scale of projected CRS

### ISSUE THREAD

**Issue by JustinVisagie** [sandrofsousa/Segreg#5]
Hi Sandro,

Thank you for writing this useful program. I am concerned that different scales related to the projected CRS are not linking through to the specification of meters in the bandwidth of the weighting function. For example, my outputs for racial segregation in the city of Cape Town were all way to low and when I explored further to change the CRS scale it had no impact. i.e. 100m bandwidth produced identical results in EPSG:102488 (Hartebeesthoek94_Lo31) [where meters are realistic] AND in EPSG:3857 (WGS 84 / Pseudo-Mercator) [where 1 meter effectively covers the size of the whole city].

Any ideas on what is going on here? Which projected CRS did you originally do your analysis on using this plugin?

Best,
Justin Visagie

**Comment by sandrofsousa** [comment]
Hi Justin,
That's curious, did you try converting to a different CRS to see what happens? Could it be that CRS and Datum have different units? The CRS is not tested or validated by no means, only if a layer is projected. Then, the X and Y coordinates of the centroid are obtained and the Euclidean distance computed using scipy. I'm afraid might be an issue with the shape file, could you please test with a different shapefile, for instance the UK census?

**Comment by JustinVisagie** [comment]
Hi Sandro,

I took a hard look and found that the strange results I got are indeed related to the calculation of distance as cartesian rather than ellipsoidal. You can see from the attached screenshot below that the estimates between these two measures are way out for the shape files I was using for Cape Town. 

<img width="663" alt="screenshot" src="https://user-images.githubusercontent.com/74443125/99932775-c24f8100-2d61-11eb-81d9-11ad9fb38c6d.png">
 
I managed to find an alternative shape file where the cartesian measurements were more or less accurate (see screenshot below) and the programme ran as it should!

<img width="509" alt="screenshot2" src="https://user-images.githubusercontent.com/74443125/99932898-1eb2a080-2d62-11eb-9de0-e7d231d9c022.png">

I don't really understand why there is this massive difference in cartesian versus ellipsoidal measurements for the different shapefiles I have (????) - but at least I've found a way forward. Thank you!

**Comment by sandrofsousa** [comment]
Hi Justin,
I'm glad it worked out at the end, I can't really tell what went wrong there as it depends on the shapefile definition, and quite often some weird standards are used. I'm closing the query.
